// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qlrssqljqxkeienjixqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFscnNzcWxqcXhrZWllbmppeHF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE1ODM2OTAsImV4cCI6MjA1NzE1OTY5MH0.VXEh1a_kwX5zEl148jL6Zev3pMitxvHyUoUlgQXByF0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);